[feat_table_desc][sql] add table comment
DTStack/Taier pull request #1043
Opened 2023-04-15 07:34 UTC by vainhope

2023-04-15 07:58 UTC, bnyte requested changes
有重复SQL没解决

2023-04-15 07:58 UTC, bnyte commented on sql/init.sql
>  INSERT INTO `dict` (dict_code, dict_name, dict_value, dict_desc, type, sort, data_type, depend_name, is_default, gmt_create, gmt_modified, is_deleted) VALUES ('25', 'HadoopMR', '{"actions": ["SAVE_TA
SQL重复在 https://github.com/DTStack/Taier/blob/1f5bd6a455d1e714de7b969c933949c7f6c68099/sql/init.sql#L1701-L1703

2023-04-17 01:49 UTC, vainhope commented
done

2023-04-17 02:05 UTC, bnyte approved these changes

2023-04-17 05:35 UTC, merged