fix: dropdown button wrap
DTStack/Taier pull request #1118
Opened 2023-10-13 04:00 UTC by jin-sir

### 简介

修复周期任务列表左下角的按钮折行

### 🔗 相关 Issue

fix [#1117](https://github.com/DTStack/Taier/issues/1117)

2023-10-17 03:04 UTC, mortalYoung requested changes

2023-10-17 03:04 UTC, mortalYoung commented on taier-ui/src/pages/operation/schedule.tsx
> +                        className="c-taskOperation__wrap__dropdown-btn"
感觉不用加 className，直接用 Space 组件好了

2023-10-17 03:05 UTC, jin-sir commented
您好，您的来信已收到。

2023-10-18 11:21 UTC, mortalYoung approved these changes
+1

2023-10-20 03:15 UTC, merged