Fix sketch
DTStack/Taier pull request #289
Opened 2022-03-15 06:11 UTC by kongshan-zhuyu

### 简介
- 优化sketch组件

### 主要变更
- 增加默认的scroll滚动时只滚动table content
- 优化周期实例table滚动增加scrollY

2022-03-15 06:56 UTC, mortalYoung requested changes

2022-03-15 06:56 UTC, mortalYoung commented on taier-ui/src/components/sketch/index.tsx
> +				scroll={{ y: 'calc(100vh - 300px)' }}
这里能不能做成自动检测 `dt-sketch` 这个组件的高度，然后基于这个高度再去计算出 table 占的高度，做动态的 js 计算。
或者直接去取 `dt-sketch-table` 的高度去算。 
因为考虑到，如果这个写死成 `-300px` 的话，用这个组件的页面都得去算，比较麻烦，然后会遗漏掉一些页面 0.0

2022-03-16 11:06 UTC, kongshan-zhuyu commented on taier-ui/src/components/sketch/index.tsx
> +				scroll={{ y: 'calc(100vh - 300px)' }}
已添加自定义hooks计算table的滚动高

2022-03-16 11:53 UTC, mortalYoung requested changes

2022-03-16 11:53 UTC, mortalYoung commented on taier-ui/src/components/sketch/index.tsx
> +import useCalcTableScroll from '@/components/calcTableScroll'
自定义的 hooks 不算 components，找个更好的地方放吧。或者放 customHooks 那个下面

2022-03-16 12:18 UTC, kongshan-zhuyu commented on taier-ui/src/components/sketch/index.tsx
> +import useCalcTableScroll from '@/components/calcTableScroll'
已迁移至customHooks中

2022-03-17 01:46 UTC, mortalYoung commented
prettier 竟然没有自动加分号。我先合了，后续我再看看这个 lint-staged 0.0

2022-03-17 01:46 UTC, mortalYoung approved these changes

2022-03-17 01:46 UTC, merged