[taier-ui] refactor cluster management
DTStack/Taier pull request #308
Opened 2022-03-24 10:03 UTC by kiwiwong

## 简介

- 多集群管理重构（优化）

## 主要变更

- 抽离部分view组件
- 优化部分代码风格和逻辑
- 补充TS类型
- form改为使用context传递
- 去掉轮播组件
- 修复表单输入卡顿问题
- 修复组件变更对比功能（针对单版本组件）
- 点击完成时的交互优化
- 测试连通性错误信息样式及交互bug修复；

## 遗留问题

- 多版本组件的变更对比功能暂未修复
- 点击取消按钮的功能未完善
- 部分无用代码暂未删除
- 逻辑层面没有较好的抽象（主要还是基于原有代码进行优化）

2022-03-25 03:27 UTC, mortalYoung requested changes

2022-03-25 03:27 UTC, mortalYoung commented on taier-ui/src/components/testResultIcon/index.tsx
> +import type { ITestStatusProps } from '@/pages/console/cluster/newEdit/interface';
这个放到样式文件的上面引入呗

2022-03-25 03:27 UTC, mortalYoung commented on taier-ui/src/pages/console/cluster/newEdit/components/compsBtn/index.tsx
> +import type { IScheduleComponentComp, IHandleConfirm } from '../../interface';
这里也是放到样式文件的上面引入

2022-03-25 03:27 UTC, mortalYoung commented on taier-ui/src/pages/console/cluster/newEdit/components/metaIcon/index.tsx
> +import type { IScheduleComponentComp } from '../../interface';
同上

2022-03-25 03:27 UTC, mortalYoung commented on taier-ui/src/pages/console/cluster/newEdit/components/multiVerComp/index.tsx
> +						comp={comp as any}
这里为啥要 as any

2022-03-25 03:27 UTC, mortalYoung commented on taier-ui/src/pages/console/cluster/newEdit/fileConfig/components/uploadFileBtn/index.tsx
> +	// const fileName = form.getFieldValue(formField)?.name ?? fileInfo?.value;
这里注释掉会报错吧 0.0

2022-03-25 03:27 UTC, mortalYoung commented on taier-ui/src/pages/console/cluster/newEdit/fileConfig/index.tsx
>  import './index.scss';
样式文件放在最后 import

2022-03-25 03:27 UTC, mortalYoung commented on taier-ui/src/pages/console/cluster/newEdit/formConfig/components/customParams/index.tsx
>  import './index.scss';
同上

2022-03-25 03:27 UTC, mortalYoung commented on taier-ui/src/pages/console/cluster/newEdit/formConfig/components/nodeLabel/index.tsx
>  import './index.scss';
同上，下面也有，都检查一下

2022-03-25 03:27 UTC, mortalYoung commented on taier-ui/src/pages/console/cluster/newEdit/help.ts
> +export function isKubernetes(): boolean {
这种没有用，必定返回 false 的，重构的时候就拿掉好了

2022-03-25 06:00 UTC, kiwiwong commented on taier-ui/src/pages/console/cluster/newEdit/fileConfig/components/uploadFileBtn/index.tsx
> +	// const fileName = form.getFieldValue(formField)?.name ?? fileInfo?.value;
> 这里注释掉会报错吧 0.0

这个是没用到的，忘记删了，其他的我也都处理一下

2022-03-28 07:35 UTC, mortalYoung approved these changes
+1

2022-03-28 07:40 UTC, merged