Fix 1.10 css
DTStack/Taier pull request #499
Opened 2022-05-23 03:53 UTC by StrangeXin

### 简介

- 修复数据同步增量标识任务预览没有显示增量标识的问题
- 修复一些已知样式问题：

1. 数据同步任务目标表名必填但无*标识
2. 离线任务周期过滤项缺失分钟和小时任务
3. 补数据实例列表页dark主题下字段颜色看不清
4. 实时任务详情-数据曲线页面无法上下滚动
5. 实时任务计算中点击停止弹窗按钮错位
6. ellipsis全局样式缺失，导致源表数据预览换行
7. input输入框高度不正确，部分表单元素字体没有统一12px
8. 周期实例详情graph图运行中状态颜色不正确，从绿色改为蓝色
9. 优化实时任务源表和结果表表单样式

2022-05-23 10:03 UTC, mortalYoung requested changes

2022-05-23 10:03 UTC, mortalYoung commented on taier-ui/src/pages/operation/streamTask/index.tsx
> +								top: 124,
我这边改成 124 会有偏移 0.0

2022-05-23 11:25 UTC, mortalYoung commented
另外 PR 的名字可以该一下 遵循 https://dtstack.github.io/Taier/docs/contributing/#commitment-%E8%A7%84%E8%8C%83

2022-05-24 01:18 UTC, StrangeXin commented on taier-ui/src/pages/operation/patch/index.tsx
> +					const style = isComplete ? undefined : { color: '#EF5350' };
<img width="787" alt="image" src="https://user-images.githubusercontent.com/6157378/169928973-04feca3d-a846-4974-9fb2-11f7cf6e7e20.png">
<img width="711" alt="image" src="https://user-images.githubusercontent.com/6157378/169929008-0cbe0962-a289-437f-a70c-093fd0fbb8c9.png">
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/6157378/169929058-53b3dcf2-e0c1-479e-82b6-153a75380390.png">
使用var(--editorError-foreground)时，主题DTStack Theme有效，其他主题下无效

2022-05-24 01:22 UTC, StrangeXin commented on taier-ui/src/pages/operation/streamTask/index.tsx
> +								top: 124,
那这里不能用绝对定位了，最好改为弹窗自定义页脚按钮方式

2022-05-24 01:56 UTC, StrangeXin commented on taier-ui/src/pages/operation/patch/index.tsx
> +					const style = isComplete ? undefined : { color: '#EF5350' };
我这边是先改成var(--editorError-foreground)，然后等主题问题修复，还是说先不改？

2022-05-24 03:28 UTC, StrangeXin commented on taier-ui/src/pages/operation/streamTask/index.tsx
> +								top: 124,
<img width="598" alt="image" src="https://user-images.githubusercontent.com/6157378/169942827-e1007cb7-5e3c-484f-904c-4ea6370bd00b.png">
你那边截图看下 0.0
那这条另外提个issue？

2022-05-24 03:32 UTC, StrangeXin commented on taier-ui/src/pages/operation/streamTask/index.tsx
> +								top: 124,
这边看到，如果中间文字是14px，top设为124就会错位，如果是12px，则只有2行，不会错位
你应该是没有把css的变更也加上
<img width="684" alt="image" src="https://user-images.githubusercontent.com/6157378/169943317-6a660ac3-7a4c-4a80-b411-6d3a03d13ce8.png">

2022-05-24 06:28 UTC, mortalYoung commented on taier-ui/src/pages/operation/patch/index.tsx
> +					const style = isComplete ? undefined : { color: '#EF5350' };
先改吧，这个属于是其他主题的问题，按道理来说这里应该是 `var(--editorError-foreground)` 这个颜色

2022-05-24 06:29 UTC, mortalYoung commented on taier-ui/src/pages/operation/streamTask/index.tsx
> +								top: 124,
确实是

2022-05-24 09:31 UTC, StrangeXin commented
已修改完成

2022-05-24 09:34 UTC, merged